// Explicit manual acceptance run: uses the local GPU and ComfyUI, saves artifacts.
import {spawn,execFileSync} from 'node:child_process';
import {once} from 'node:events';
import {mkdir,readFile,writeFile,copyFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('../',import.meta.url)),work=join(root,'build/media-acceptance');await mkdir(work,{recursive:true});
const bin=join(root,'build/Release-acceptance');await mkdir(bin,{recursive:true});for(const f of ['yue-server.exe','ggml.dll','ggml-base.dll','ggml-cpu.dll','ggml-cuda.dll'])await copyFile(join(root,'build/Release-producer',f),join(bin,f));
const env=Object.fromEntries(Object.entries(process.env).map(([k,v])=>[k.toUpperCase(),v]));env.PATH=join(root,'.venv-vocal/Scripts')+';'+bin+';'+env.PATH;delete env.GGML_BACKEND;
const server=spawn(join(bin,'yue-server.exe'),['--host','127.0.0.1','--port','18089','--max-seq','4096','--model',join(root,'models/YuE2-3B-Q8_0.gguf'),'--vae',join(root,'models/YuE2-Vae-F32.gguf')],{cwd:work,env,windowsHide:true,stdio:['ignore','pipe','pipe']});
let logs='';server.stderr.on('data',b=>{logs+=b;});server.stdout.on('data',()=>{});
const base='http://127.0.0.1:18089',report={started:new Date().toISOString(),checks:[],artifacts:work};
async function checkpoint(name,details){report.checks.push({name,details,at:new Date().toISOString()});await writeFile(join(work,'report.json'),JSON.stringify(report,null,2));await writeFile(join(work,'server.log'),logs);console.log(name,JSON.stringify(details));}
async function poll(id){for(let i=0;i<1800;i++){const data=await(await fetch(base+`/job?id=${id}`)).json();if(data.status==='done')return;if(data.status!=='running')throw Error(JSON.stringify(data)+' '+logs.slice(-3000));if(i%15===0)console.log('Working',JSON.stringify(await(await fetch(base+'/jobs')).json()));await new Promise(r=>setTimeout(r,2000));}throw Error('Job timed out');}
const ff=(cmd,args)=>execFileSync(cmd,args,{env,windowsHide:true,encoding:'utf8',maxBuffer:16*1024*1024});
function multipart(bytes,boundary){const marker=Buffer.from('--'+boundary),parts=[];let pos=bytes.indexOf(marker);for(;;){const next=bytes.indexOf(marker,pos+marker.length);if(next<0)break;const headerEnd=bytes.indexOf('\r\n\r\n',pos),header=bytes.subarray(pos,headerEnd).toString();parts.push({header,body:bytes.subarray(headerEnd+4,next-2)});pos=next;}return parts;}
async function imageJob(reference){const info=await(await fetch(base+'/comfy/object_info')).json();const {availableArtModels,artworkGraph}=await import('../tools/webui/src/lib/comfy-art.ts');const models=availableArtModels(info);let ref;
 if(reference){const f=new FormData();f.append('image',new Blob([reference],{type:'image/png'}),'acceptance-reference.png');f.append('overwrite','false');const r=await(await fetch(base+'/comfy/upload/image',{method:'POST',body:f})).json();ref=(r.subfolder?r.subfolder+'/':'')+r.name+' [input]';}
 const prompt=reference?'Use <image1> as a palette and illustration style reference. A different scene: a vintage drum machine on a rooftop at violet sunset, cinematic hip hop album cover, no text.':'Cinematic illustrated hip hop album cover: a lone adult rapper in a yellow jacket beneath a rain-soaked city overpass, warm amber streetlights and violet shadows, richly detailed, no text or logos.';
 const start=Date.now(),response=await fetch(base+'/comfy/prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:artworkGraph(models,prompt,7217,reference?'yue2-acceptance-reference':'yue2-acceptance-cover',ref),client_id:'yue2-acceptance'})});if(!response.ok)throw Error(await response.text());const {prompt_id}=await response.json();await checkpoint('Artwork submitted',{prompt_id,reference:!!reference});
 for(let i=0;i<900;i++){const history=await(await fetch(base+'/comfy/history/'+prompt_id)).json(),item=history[prompt_id];if(item?.status?.status_str==='error')throw Error(JSON.stringify(item.status));const image=item?.outputs?.['8']?.images?.[0];if(image){const bytes=Buffer.from(await(await fetch(base+'/comfy/view?'+new URLSearchParams(image))).arrayBuffer());await checkpoint(reference?'Reference artwork completed':'Artwork completed',{seconds:(Date.now()-start)/1000,bytes:bytes.length});return bytes;}if(i%15===0)console.log('Artwork still processing',prompt_id);await new Promise(r=>setTimeout(r,2000));}throw Error('Artwork timeout');}
try{
 for(let i=0;i<100;i++){try{if((await fetch(base+'/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,200));}
 const request={style:'Boom bap hip hop, 90 BPM, warm clear male mid-range rhythmic rap, dusty drums, jazz piano, deep bass, articulate delivery.',lyrics:'[Verse]\nCity lights are shining through the rain\nBuild a little rhythm from the train\nStep by step we find a brighter way\nTurn another midnight into day',cot:'off',duration:12,lm_seed:7217,seed:7217,lm_batch_size:1,synth_batch_size:2,steps:32,output_format:'wav24',mastering_profile:'streaming'};
 const start=Date.now(),id=crypto.randomUUID().replaceAll('-','');const response=await fetch(base+'/synth',{method:'POST',headers:{'Content-Type':'application/json','X-Yue2-Job-Id':id},body:JSON.stringify(request)});if(!response.ok)throw Error(await response.text());await checkpoint('Music submitted',{id,request});await poll(id);
 const result=await fetch(base+`/job?id=${id}&result=1`),boundary=result.headers.get('Content-Type').match(/boundary=([^\s;]+)/)[1];const parts=multipart(Buffer.from(await result.arrayBuffer()),boundary);let audio,original,index=0;
 for(const part of parts){if(part.header.includes('application/json')){await writeFile(join(work,`request-${index}.json`),part.body);continue;}await writeFile(join(work,`take-${index}.wav`),part.body);if(index===1)audio=part.body;if(index===0)original=part.body;index++;}
 assert.equal(index,4,'two mastered takes paired with originals');await checkpoint('Real music completed',{seconds:(Date.now()-start)/1000,audioParts:index});
 const probe=JSON.parse(ff('ffprobe',['-v','error','-show_streams','-of','json',join(work,'take-0.wav')]));assert.equal(probe.streams[0].sample_rate,'48000');await checkpoint('Audio format',probe.streams[0]);
 // Measure actual input loudness and peak without changing the saved audio.
 for(const n of [0,1]){const proc=spawn('ffmpeg',['-hide_banner','-i',join(work,`take-${n}.wav`),'-af','loudnorm=I=-14:TP=-1:print_format=json','-f','null','-'],{env,windowsHide:true,stdio:['ignore','ignore','pipe']});let output='';proc.stderr.on('data',b=>output+=b);await once(proc,'exit');await writeFile(join(work,`loudness-${n}.txt`),output);await checkpoint('Loudness measured',{take:n,version:n===0?'original':'streaming master',measurement:output.slice(output.lastIndexOf('{'))});}
 const cover=await imageJob();await writeFile(join(work,'cover.png'),cover);
 const referenced=await imageJob(cover);await writeFile(join(work,'reference-cover.png'),referenced);
 const form=new FormData();form.append('audio',new Blob([audio],{type:'audio/wav'}),'track.wav');form.append('cover',new Blob([cover],{type:'image/png'}),'cover.png');const videoId=(await(await fetch(base+'/render-video',{method:'POST',body:form})).json()).id;assert.ok(videoId);await poll(videoId);await writeFile(join(work,'hiphop-circuit-test.mp4'),Buffer.from(await(await fetch(base+`/job?id=${videoId}&result=1`)).arrayBuffer()));await checkpoint('Generated artwork MP4 ready',{videoId});
 const vocalForm=new FormData();vocalForm.append('audio',new Blob([original],{type:'audio/wav'}),'original.wav');vocalForm.append('vocal_gain_db','3');const vocalResponse=await fetch(base+'/vocal-balance',{method:'POST',body:vocalForm});if(!vocalResponse.ok)throw Error(await vocalResponse.text());const vocalId=(await vocalResponse.json()).id;await poll(vocalId);await writeFile(join(work,'vocal-plus3.wav'),Buffer.from(await(await fetch(base+`/job?id=${vocalId}&result=1`)).arrayBuffer()));await checkpoint('Real vocal separation completed',{vocalId});
 await checkpoint('Acceptance run finished',{ });
}catch(error){await checkpoint('Acceptance needs attention',{error:String(error),log:logs.slice(-4000)});process.exitCode=1;}
finally{await writeFile(join(work,'server.log'),logs);if(server.exitCode===null&&server.signalCode===null){const ended=once(server,'exit');server.kill();await ended;}}
